### ISSUE TITLE
Where's the dll file?

### ISSUE THREAD

**Issue by EnderPreston** [GaryFrazier/sadx-bounce-bracelet#1]
I don't know if this is actually an issue, but I don't know how to leave comments, and this is the only way I know how, but that's not my main problem right now.

I may sound like a noob for asking this, but I can't use this mod, and it's because the mod doesn't have the needed dll file. Could you please help me out?

**Comment by Grep5268** [comment]
sorry about that dlls were ignored in my gitignore, check now!
